name: build-deploy-app
run-name: build and deploy board-game app
on:
  push:
    branches:
      - "master"

jobs:
  board-build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: build-simple-api
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
          cache: 'maven'
      - name: get access
        run: chmod +x mvnw
      - name: build with maven
        run: ./mvnw -B verify
#      - name: login to DockerHub
#        uses: docker/login-action@v3
#        with:
#          username: ${{secrets.DOCKERHUB_USERNAME}}
#          password: ${{secrets.DOCKERHUB_TOKEN}}
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_SIMPLEAPI_REPO_NAME }}:latest