name: deploy-app
run-name: deploy board-game app
on:
  push:
    branches:
      - "master"

jobs:
  board-build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: build-simple-api
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
          cache: 'maven'
      - name: get access
        run: chmod +x mvnw
      - name: build with maven
        run: ./mvnw -B verify